#! usr/bin/ruby

# this script assumes the working directory is the directory containing this file (java/).

puts "compile..........."
files=Dir.glob("src/org/spinachtree/gist/*.java").join(" ")
system "javac -d class -sourcepath src #{files}"

puts "gist.jar......."
system "jar cf gist.jar -C class org/spinachtree/gist"

puts "test........."
tests=Dir.glob("../tests/*").join(" ")
system "java -cp gist.jar org.spinachtree.gist.Glib -test #{tests}"
tests=Dir.glob("../demos/*").join(" ")
system "java -cp gist.jar org.spinachtree.gist.Glib -test #{tests}"

puts "javadoc......."
system "javadoc -d javadoc -sourcepath src org.spinachtree.gist"

puts "compile examples......."
examples=Dir.glob("examples/*.java").join(" ")
system "javac -d class -classpath gist.jar #{examples}"