#! usr/bin/ruby

if ARGV.size==1
	system "java -cp gist.jar org.spinachtree.gist.Glib ../demos/#{ARGV[0]}"
elsif ARGV.size==2
	system "java -cp gist.jar org.spinachtree.gist.Glib #{ARGV[0]} ../demos/#{ARGV[1]}"
else
	puts "*** wrong number of args, use: file, or -demo file, or -test file  (-demo default)"
end
