#! usr/bin/ruby

if ARGV.size==0
	puts "***missing file name...."
elsif ARGV.size>1 and ARGV[0]=="-c"
	system "javac -d class -classpath gist.jar examples/#{ARGV[1]}"
else
	system "java -cp gist.jar:class #{ARGV[0]} #{ARGV[1]}"
end

